import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalWrapper from "@/components/global-wrapper";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalWrapper>
          <Header />
          <main className="grid grid-cols-[1fr_min(100%,800px)_1fr]">
            {children}
          </main>
          <footer className="grid grid-cols-[1fr_min(100%,800px)_1fr] bg-white">
            <section className="col-2 border border-red-500 text-black">
              Footer
            </section>
          </footer>
        </GlobalWrapper>
      </body>
    </html>
  );
}
